---
    name: Linting and Prettier
    on:
      push:
        branches:
          - main
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository code
            uses: actions/checkout@v3
          - name: List files in the repository
            run: |
              ls ${{ github.workspace }}
          - run: echo "This job's status is ${{ job.status }}."
          - name: Set up NodeJS version 20
            uses: actions/setup-node@v4
            with:
              node-version: 20
          - run: yarn install
          - run: yarn lint
          - name: Prettier Fix
            uses: WorkOfStan/prettier-fix@v1.0.0
      